
import React, { useState, useEffect } from 'react';
import { generateLessonVideo } from '../services/gemini';

interface Props {
  title: string;
  description: string;
}

export const ConceptVideoPlayer: React.FC<Props> = ({ title, description }) => {
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadingMessage, setLoadingMessage] = useState("Initializing Veo creative engines...");

  // Reset state when the lesson changes
  useEffect(() => {
    setVideoUrl(null);
    setIsLoading(false);
    setError(null);
  }, [title]);

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    
    // Cycling loading messages to keep user entertained
    const messages = [
        "Consulting the neural artist...",
        "Rendering pixels in latent space...",
        "Synthesizing futuristic visuals...",
        "Polishing frames...",
        "Applying cinematic lighting...",
        "Almost there, just a few more seconds..."
    ];
    let msgIdx = 0;
    const interval = setInterval(() => {
        setLoadingMessage(messages[msgIdx % messages.length]);
        msgIdx++;
    }, 4000);

    try {
        const url = await generateLessonVideo(title, description);
        setVideoUrl(url);
    } catch (e: any) {
        console.error(e);
        setError("Failed to generate video. Please verify you selected a Paid API Key.");
    } finally {
        clearInterval(interval);
        setIsLoading(false);
    }
  };

  if (videoUrl) {
    return (
         <div className="aspect-video bg-black rounded-xl border border-slate-800 relative overflow-hidden shadow-2xl group">
            <video src={videoUrl} controls autoPlay loop className="w-full h-full object-cover" />
            <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                <div className="bg-black/50 backdrop-blur text-[10px] text-white px-2 py-1 rounded border border-white/20">
                    Generated by Veo
                </div>
            </div>
         </div>
    );
  }

  return (
    <div 
        onClick={!isLoading ? handleGenerate : undefined}
        className={`aspect-video bg-slate-950 rounded-xl border border-slate-800 relative overflow-hidden group shadow-2xl ${!isLoading ? 'cursor-pointer hover:border-indigo-500/50' : ''} transition-all duration-300`}
    >
         {/* Dynamic Background */}
         <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/80 to-transparent opacity-60"></div>
         <div className={`absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-10 ${isLoading ? 'animate-pulse' : ''}`}></div>
         
         <div className="absolute inset-0 flex flex-col items-center justify-center p-6 text-center z-10">
            {isLoading ? (
                <div className="flex flex-col items-center gap-4">
                    <div className="relative">
                        <div className="w-16 h-16 border-4 border-indigo-500/30 rounded-full animate-ping absolute inset-0"></div>
                        <div className="w-16 h-16 border-4 border-t-indigo-500 border-r-indigo-500 border-b-transparent border-l-transparent rounded-full animate-spin"></div>
                    </div>
                    <p className="text-indigo-300 font-mono text-xs animate-pulse tracking-widest uppercase">{loadingMessage}</p>
                </div>
            ) : error ? (
                <div className="flex flex-col items-center gap-2">
                    <div className="text-red-500 text-3xl mb-2">⚠️</div>
                    <p className="text-red-400 font-bold">{error}</p>
                    <button className="mt-2 bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg text-xs font-bold transition-colors" onClick={(e) => { e.stopPropagation(); handleGenerate(); }}>
                        RETRY
                    </button>
                </div>
            ) : (
                <>
                    <div className="w-20 h-20 rounded-full bg-gradient-to-br from-indigo-600/20 to-purple-600/20 backdrop-blur-md flex items-center justify-center border border-indigo-500/30 group-hover:scale-110 group-hover:border-indigo-400/80 transition-all duration-300 shadow-[0_0_30px_rgba(79,70,229,0.2)] mb-5">
                        <svg className="w-8 h-8 text-indigo-400 fill-current ml-1" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
                    </div>
                    <h3 className="text-white font-black text-xl mb-2 group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-indigo-400 group-hover:to-purple-400 transition-all">GENERATE CONCEPT VIDEO</h3>
                    <p className="text-slate-400 text-sm max-w-sm leading-relaxed">
                        Visualize "<span className="text-slate-300">{title}</span>" with Veo AI. 
                        <br/>
                        <span className="text-[10px] opacity-70">Takes ~1-2 minutes.</span>
                    </p>
                    <div className="mt-6 flex gap-2">
                         <span className="px-3 py-1 bg-indigo-500/10 border border-indigo-500/30 rounded-full text-[10px] text-indigo-400 font-bold font-mono">VEO-3.1</span>
                         <span className="px-3 py-1 bg-amber-500/10 border border-amber-500/30 rounded-full text-[10px] text-amber-500 font-bold font-mono">PAID KEY REQ.</span>
                    </div>
                </>
            )}
         </div>
    </div>
  );
};
